FROM jc21/dpkg-debian:latest

LABEL maintainer="Jamie Curnow <jc@jc21.com>"

USER root

RUN wget "https://go.dev/dl/go1.17.7.linux-amd64.tar.gz" -O /tmp/go.tgz \
	&& rm -rf /usr/local/go \
	&& tar -C /usr/local -xzf /tmp/go.tgz

USER builder

ENV GOROOT=/usr/local/go
ENV GOPATH=/home/builder/go
ENV PATH="/usr/local/go/bin:/home/builder/go/bin:${PATH}"
ENV USER=builder

RUN go version
